package com.unicen.app.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.unicen.app.indicators.Factory;
import com.unicen.app.indicators.Indicator;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * Created by Alfonso on 30/7/16.
 */
public class PairwiseWindow {
    private JPanel pairwisePanel;
    private JButton confirmButton;
    private CheckBoxList checkBoxList;
    private MainWindow mainWindow;

    public void main(MainWindow mw, CheckBoxList checkBoxList) {
        JFrame frame = new JFrame("MainWindow");
        frame.setMinimumSize(new Dimension(300, 300));
        frame.setContentPane(pairwisePanel);
        frame.pack();
        frame.setVisible(true);
        this.checkBoxList = checkBoxList;
        this.mainWindow = mw;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        confirmButton = new JButton();

        confirmButton.addActionListener(actionEvent -> {

            //chequear la matriz

            /*Si está correcta*/

            List<String> selected = checkBoxList.choosenValues();
            List<Indicator> indicators = new ArrayList<Indicator>();
            for (String indicator : selected) {
                indicators.add(Factory.get(indicator));
            }
            int n = indicators.size();
            double[][] indicatorsMatrix = new double[n][n];


            //copiar los valores que ingreso el usuario a la matriz

            //Prueba
            for (int i = 0; i < n; i++)
                for (int j = 0; j < n; j++)
                    indicatorsMatrix[i][j] = 1;

            mainWindow.showAHPResults(indicators, indicatorsMatrix);

        });

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pairwisePanel = new JPanel();
        pairwisePanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        confirmButton.setText("Confirm");
        pairwisePanel.add(confirmButton, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pairwisePanel.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pairwisePanel;
    }
}
